# name: Events Demo 1
# on:
#   pull_request:
#     types: closed
#     branches:
#       - main
# jobs:
#   create-tag:
#     if: github.event.pull_request.merged == true
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
#       # - run: git tag
#       # - run: git fetch -p
#       # - run: git checkout -b

name: Events Demo 1
on:
  pull_request:
    types: [opened, closed]
    branches:
      - main
      - dev
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      # - run: git tag
      # - run: git fetch -p
      # - run: git checkout -b
