name: Events Demo 1
on:
  pull_request:
    types: [opened, reopened, closed]
    branches:
      - master
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "TAG_NAME=release_$(date +'%Y_%m_%d')" >> $GITHUB_ENV
      - run: echo "hey my name is $TAG_NAME"
      - run: git tag $TAG_NAME master
      - run: git fetch -p
      - run: git push origin $TAG_NAME
      - run: git checkout -b $TAG_NAME $TAG_NAME
