name: Events Demo 1
on:
  pull_request:
    types: closed
    branches:
      - master
jobs:
  create-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - run: echo "hey my name is $CURRENT_DATE"
      # - run: git tag
      # - run: git fetch -p
      # - run: git checkout -b
